defaults:
  - hardware: cuda
  - logger: neptune
  - data: breast_cancer
  - mode: adversarial_erasing
  - training: base

training:
  batch_size: 32
  learning_rate: 1e-4

mode:
  train_config:
    max_iterations: 6
    heatmaps:
      threshold: 0.9
      negative_load_strategy: random
      area_envelope:
        scale: 0.2
  masks:
    remove_background: false